services:
  # sql:
  #   image: mcr.microsoft.com/azure-sql-edge
  #   container_name: sql-server
  #   environment:
  #     - ACCEPT_EULA="1"
  #     - SA_PASSWORD="Password@1"
  #   ports:
  #     - "1433:1433"
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=https://+:443
    depends_on:
      - redis
volumes:
  redis-data:
